# ----
# Site

title: CloudFx
description: CloudFx is a non-profit community of developer for developers.
url: https://cloudfx.github.io
disqus_shortname: cloudfx
baseurl:

active_sibling:
main_url:
google_site_verification: GkBrJRSQqF43wQVGLUeUJFTPBldtIXGCw9toqvS2o_o
permalink: pretty

footer:
  contact_us:
    email: codefxcommunity@gmail.com
  copyright: CloudFx Community
  social:
    twitter: cloudfxcommunity
    facebook: cloudfxcommunity
    google: cloudfxcommunity
    youtube: cloudfxcommunity
# ----------
# SEO plugin

lang: en_US
logo: /siteicon.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
